MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/heqing/maskrcnn-benchmark/demo/model_0015000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (1200, 1600)
  MAX_ITER: 3000
  IMS_PER_BATCH: 2
