MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/root/pytorch_mobilenetV2/experiments/FPN_2/checkpoints/model_test_best_clear.pth.tar"
  BACKBONE:
    CONV_BODY: "MobileV2_FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 7
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    POSTPROCESS_MASKS: False
  MASK_ON: False
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  GAMMA: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 130000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 6
  CHECKPOINT_PERIOD: 29000
INPUT:
  TO_BGR255: False
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  SATURATION: 0.0
  HUE: 0.0
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0
  VERTICAL_FLIP_PROB_TRAIN: 0.0


